// <auto-generated />
using System;
using DataAccessLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225162948_InitialSQLiteSchema")]
    partial class InitialSQLiteSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DataAccessLibrary.Models.AdditionalCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("CustomIntelliSenseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CustomIntelliSenseID");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SendKeysValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SendKeys_Value");

                    b.Property<decimal>("WaitBefore")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("WaitBefore");

                    b.HasKey("Id");

                    b.HasIndex("CustomIntelliSenseId");

                    b.ToTable("AdditionalCommands");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ApplicationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationDetails");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Label")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recurrence")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Category_Type");

                    b.Property<string>("Colour")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sensitive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CssProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CssProperties");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CurrentWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("Handle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CurrentWindow");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CursorlessCheatsheetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CursorlessType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpokenForm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeLink")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CursorlessCheatsheetItems");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CustomIntelliSense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CommandType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Command_Type");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ComputerID");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Display_Value");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LanguageID");

                    b.Property<int>("MoveCharactersLeft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Search")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectCharactersLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectWordFromRight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SendKeysValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SendKeys_Value");

                    b.Property<string>("Variable1")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variable2")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variable3")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_CategoryID");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("IX_ComputerID");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("IX_LanguageID");

                    b.ToTable("CustomIntelliSense");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CustomWindowsSpeechCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AbsoluteX")
                        .HasColumnType("REAL");

                    b.Property<double>("AbsoluteY")
                        .HasColumnType("REAL");

                    b.Property<bool>("AlternateKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLineArguments")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HowToFormatDictation")
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KeyDownValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KeyPressValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KeyUpValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MethodToCall")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifierKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MouseCommand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MouseMoveX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MouseMoveY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessStart")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScrollAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SendKeysValue")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShiftKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextToEnter")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WindowsKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WindowsSpeechVoiceCommandId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WindowsSpeechVoiceCommandId");

                    b.ToTable("CustomWindowsSpeechCommands");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Boolean")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("LargeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.FaceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaceImages");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.FaceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("FaceImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FaceImageId");

                    b.ToTable("FaceTags");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.GeneralLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Item_Value");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GeneralLookups");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.GrammarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrammarNameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrammarNameId");

                    b.ToTable("GrammarItems");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.GrammarName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameOfGrammar")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameOfGrammar")
                        .IsUnique();

                    b.ToTable("GrammarNames");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.HtmlTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Include")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpokenForm")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HtmlTags");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Idiosyncrasy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FindString")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplaceWith")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("StringFormattingMethod")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Idiosyncrasies");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("Language");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Launcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Arguments")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ComputerID");

                    b.Property<bool>("Favourite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_CategoryID");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("IX_ComputerID");

                    b.ToTable("Launcher");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.LauncherCategoryBridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<int>("LauncherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LauncherID");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LauncherId");

                    b.ToTable("LauncherCategoryBridge");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.LauncherMultipleLauncherBridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("LauncherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LauncherID");

                    b.Property<int>("MultipleLauncherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MultipleLauncherID");

                    b.HasKey("Id");

                    b.HasIndex("LauncherId");

                    b.HasIndex("MultipleLauncherId");

                    b.ToTable("LauncherMultipleLauncherBridge");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Logins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Microphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MicrophoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Microphones");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.MigrationHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Model")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("MigrationId", "ContextKey")
                        .HasName("PK_dbo.__MigrationHistory");

                    b.ToTable("__MigrationHistory");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.MousePositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Application")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MouseLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MouseTop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabPageName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MousePositions");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.MultipleLauncher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MultipleLauncher");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.PhraseListGrammar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhraseListGrammarValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PhraseListGrammars");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.PropertyTabPositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("NumberOfTabs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PropertyTabPositions");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.QuickPrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuickPrompts");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.SavedMousePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("NamedLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SavedMousePosition");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.SpokenForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpokenFormText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("WindowsSpeechVoiceCommandId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WindowsSpeechVoiceCommandId");

                    b.HasIndex("SpokenFormText", "WindowsSpeechVoiceCommandId")
                        .IsUnique();

                    b.ToTable("SpokenForm");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.TalonAlphabet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultLetter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TalonAlphabets");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.TalonList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ListValue")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpokenForm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TalonLists");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.TalonVoiceCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TalonVoiceCommands");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportFilename")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneyIn")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MoneyOut")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MyTransactionType")
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.TransactionTypeMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MyTransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MyTransactionType", "Type")
                        .IsUnique();

                    b.ToTable("TransactionTypeMapping");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ValuesToInsert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lookup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueToInsertValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("ValueToInsert");

                    b.HasKey("Id");

                    b.ToTable("ValuesToInsert");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewCategories", b =>
                {
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Category_Type");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.ToTable((string)null);

                    b.ToView("View_Categories", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewComputers", b =>
                {
                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.ToTable((string)null);

                    b.ToView("View_Computers", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewCustomIntelliSense", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CommandType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Command_Type");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ComputerID");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Display_Value");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LanguageID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Search")
                        .HasColumnType("TEXT");

                    b.Property<string>("SendKeysValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("SendKeys_Value");

                    b.ToTable((string)null);

                    b.ToView("View_CustomIntelliSense", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewHtmlTags", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<bool>("Include")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpokenForm")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("View_HtmlTags", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewLanguages", b =>
                {
                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("View_Languages", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewLauncher", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ComputerID");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("View_Launcher", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewLauncherMultipleLauncherBridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("LauncherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LauncherID");

                    b.Property<int>("MultipleLauncherId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MultipleLauncherID");

                    b.ToTable((string)null);

                    b.ToView("View_LauncherMultipleLauncherBridge", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewMousePositions", b =>
                {
                    b.Property<string>("Application")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("MouseLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MouseTop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabPageName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("View_MousePositions", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewMultipleLauncher", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.ToTable((string)null);

                    b.ToView("View_MultipleLauncher", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewPropertyTabPositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("NumberOfTabs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("View_PropertyTabPositions", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewSavedMousePosition", b =>
                {
                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("NamedLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("View_SavedMousePosition", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ViewValuesToInsert", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Lookup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueToInsert")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("View_ValuesToInsert", (string)null);
                });

            modelBuilder.Entity("DataAccessLibrary.Models.VisualStudioCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VisualStudioCommands");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.WindowsSpeechVoiceCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpokenCommand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WindowsSpeechVoiceCommand");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.AdditionalCommand", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.CustomIntelliSense", "CustomIntelliSense")
                        .WithMany("AdditionalCommands")
                        .HasForeignKey("CustomIntelliSenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomIntelliSense");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CustomIntelliSense", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.Category", "Category")
                        .WithMany("CustomIntelliSense")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.CustomIntelliSense_dbo.Categories_CategoryID");

                    b.HasOne("DataAccessLibrary.Models.Computer", "Computer")
                        .WithMany("CustomIntelliSense")
                        .HasForeignKey("ComputerId")
                        .HasConstraintName("FK_dbo.CustomIntelliSense_dbo.Computers_ComputerID");

                    b.HasOne("DataAccessLibrary.Models.Language", "Language")
                        .WithMany("CustomIntelliSense")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.CustomIntelliSense_dbo.Languages_LanguageID");

                    b.Navigation("Category");

                    b.Navigation("Computer");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CustomWindowsSpeechCommand", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.WindowsSpeechVoiceCommand", "WindowsSpeechVoiceCommand")
                        .WithMany("CustomWindowsSpeechCommands")
                        .HasForeignKey("WindowsSpeechVoiceCommandId");

                    b.Navigation("WindowsSpeechVoiceCommand");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.FaceTag", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.FaceImage", "FaceImage")
                        .WithMany("FaceTags")
                        .HasForeignKey("FaceImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaceImage");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.GrammarItem", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.GrammarName", "GrammarName")
                        .WithMany("GrammarItems")
                        .HasForeignKey("GrammarNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarName");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Launcher", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.Category", "Category")
                        .WithMany("Launchers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Launcher_dbo.Categories_CategoryID");

                    b.HasOne("DataAccessLibrary.Models.Computer", "Computer")
                        .WithMany("Launcher")
                        .HasForeignKey("ComputerId")
                        .HasConstraintName("FK_dbo.Launcher_dbo.Computers_ComputerID");

                    b.Navigation("Category");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.LauncherCategoryBridge", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.Category", "Category")
                        .WithMany("LauncherCategoryBridges")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Models.Launcher", "Launcher")
                        .WithMany("LauncherCategoryBridges")
                        .HasForeignKey("LauncherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Launcher");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.LauncherMultipleLauncherBridge", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.Launcher", "Launcher")
                        .WithMany("LaunchersMultipleLauncherBridges")
                        .HasForeignKey("LauncherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Models.MultipleLauncher", "MultipleLauncher")
                        .WithMany("LaunchersMultipleLauncherBridges")
                        .HasForeignKey("MultipleLauncherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Launcher");

                    b.Navigation("MultipleLauncher");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.SpokenForm", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.WindowsSpeechVoiceCommand", "WindowsSpeechVoiceCommand")
                        .WithMany("SpokenForms")
                        .HasForeignKey("WindowsSpeechVoiceCommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WindowsSpeechVoiceCommand");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Category", b =>
                {
                    b.Navigation("CustomIntelliSense");

                    b.Navigation("LauncherCategoryBridges");

                    b.Navigation("Launchers");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Computer", b =>
                {
                    b.Navigation("CustomIntelliSense");

                    b.Navigation("Launcher");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.CustomIntelliSense", b =>
                {
                    b.Navigation("AdditionalCommands");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.FaceImage", b =>
                {
                    b.Navigation("FaceTags");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.GrammarName", b =>
                {
                    b.Navigation("GrammarItems");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Language", b =>
                {
                    b.Navigation("CustomIntelliSense");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Launcher", b =>
                {
                    b.Navigation("LauncherCategoryBridges");

                    b.Navigation("LaunchersMultipleLauncherBridges");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.MultipleLauncher", b =>
                {
                    b.Navigation("LaunchersMultipleLauncherBridges");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.WindowsSpeechVoiceCommand", b =>
                {
                    b.Navigation("CustomWindowsSpeechCommands");

                    b.Navigation("SpokenForms");
                });
#pragma warning restore 612, 618
        }
    }
}
