 SELECT * FROM Categories WHERE Category ='Code Projects'
 SELECT * FROM Launcher WHERE CategoryId=4115
  DELETE FROM Launcher WHERE ID=32940
 SELECT * FROM LauncherCategoryBridge WHERE   LauncherId=32940
  DELETE FROM LauncherCategoryBridge WHERE ID=356
 UPDATE Launcher  set Arguments=Commandline
  WHERE CategoryId=4115
   UPDATE Launcher set Commandline='C:\Users\MPhil\AppData\Local\Programs\Microsoft VS Code\Code.exe'
   WHERE CategoryId=4115